version: "3.1"
services:
  database:
    container_name: greenTreasure
    image: mariadb
    ports:
      - "3306:3306"
    volumes:
      # the file init/01.sql contains the setup for the databases
      # this was done because we want to set the permissions of the user correctly.
      - ./init:/docker-entrypoint-initdb.d
      - ./data:/var/lib/mysql
    environment:
      - "MARIADB_ROOT_PASSWORD=password"