# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

java_version=25
minecraft_version=26.2

plugin_version=0.6.2
is_release=false

# this is the version used to compile against. It is potentially not a runnable plugin, therefor we specify the modrinth version below
worldGuard_version=7.0.18-SNAPSHOT
hikariCP_version=7.0.2
caffeine_version=3.2.3
ulidCreator_version=5.2.4

#note this is the modrinth version, used in the run task
worldGuard_runVersion=7.0.17
#wierd modrinth version id, used to fetch worldEdit for the run task.
worldEdit_runVersion=ESAHQFYo