# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G

java_version=21
minecraft_version=1.21.10

plugin_version=0.6.0
is_release=false

# this is the version used to compile against. It is potentially not a runnable plugin, therefor we specify the modrinth version below
worldGuard_version=7.1.0-SNAPSHOT
hikariCP_version=7.0.2
caffeine_version=3.2.3
commonsCollections_version=4.5.0
ulidCreator_version=5.2.3

#note this is the modrinth version, used in the run task
worldGuard_runVersion=7.0.13
#wierd modrinth version id, used to fetch worldEdit for the run task.
worldEdit_runVersion=3ISh7ADm