SQL:
  password: '{hangeTh!sPas5wordNÖw!'
  database: greentreasure_database
  port: 3306
  host: localhost
  user: greentreasure

language: en_en
import_legacy: false
break_behavior: ALL_BREAK_GLOBAL