main: de.greensurvivors.greentreasure.GreenTreasure
name: GreenTreasure
api-version: "${minecraft_version}"
version: ${version}
load: POSTWORLD
softdepend:
  - TreasureChest
  - TreasureChestX
  - WorldGuard
libraries:
  - com.github.ben-manes.caffeine:caffeine:${caffeine_version}
  - org.apache.commons:commons-collections4:${commonsCollections_version}
  - com.zaxxer:HikariCP:${hikariCP_version}
  - com.github.f4b6a3:ulid-creator:${ulidCreator_version}
description: ${description}
author: GreensurvivorsTeam