main: de.greensurvivors.greentreasure.GreenTreasure
name: GreenTreasure
api-version: "${mcVersion}"
version: ${version}
load: POSTWORLD
softdepend:
  - TreasureChest
  - TreasureChestX
  - WorldGuard
libraries:
  - org.apache.commons:commons-lang3:3.13.0
  - com.github.ben-manes.caffeine:caffeine:${caffeineVersion}
  - org.yaml:snakeyaml:${snakeyamlVersion}
  - org.apache.commons:commons-collections4:${commonsCollectionVersion}
  - com.zaxxer:HikariCP:${hikariCPVersion}
  - com.github.f4b6a3:ulid-creator:${ulidCreatorVersion}
description: green treasure, a treasure chest alternative
author: GreensurvivorsTeam