main: de.greensurvivors.greentreasure.GreenTreasure
name: GreenTreasure
version: 0.0.3
api-version: 1.19
author: Bergtiger, Feuerreiter
softdepend:
  - TreasureChest
  - TreasureChestX

commands:
  greentresure:
    aliases:
      - gt
      - gchest
      - gtreasure
    description: All green treasure commands.