main: de.greensurvivors.greentreasure.GreenTreasure
name: GreenTreasure
version: 0.0.1
api-version: 1.19
author: Bergtiger, Feuerreiter

commands:
  greentresure:
    aliases:
      - gt
      - gchest
      - gtreasure
    description: All green treasure commands.